spring:
  main:
    banner-mode: console
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3307/die_bank?createDatabaseIfNotExist=true
    username: root
    password: 1987
  jpa:
    generate-ddl: false
    show-sql: false

  liquibase:
    enabled: true
    drop-first: true
    change-log: classpath:db.changelog/changelog-master.yaml
  server:
    port: 8080